const ADD_SEARCH_TERM  = 'ADD_SEARCH_TERM'
const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'

export { ADD_SEARCH_TERM, SET_SEARCH_RESULTS, CLEAR_SEARCH_RESULTS }